import assert from "node:assert/strict";
import { Evidence, managed, until, payload, decode, delay } from "./evidence-lib.mjs";

console.log(`Capstan code-change demo · ${new Date().toISOString()}`);
console.log("Real server and versioned SDK workers; wall-clock recording, no altered history.");
await managed(new Evidence("blocked", 7303), async (env) => {
  console.log("$ (cd sdk && node --import tsx ../examples/evidence/worker.ts)  # blocked-v1.ts: activity('step')");
  let worker = env.worker("blocked-v1.ts");
  env.cli("start", "changedWorkflow", "evidence-patch-old", "--queue", env.queue);
  await until("v1 activity completed and workflow idle", async () => (await env.history("evidence-patch-old")).length >= 9 && env.sql("select count(*) from task", ["-Atq"]).trim() === "0");
  const before = await env.history("evidence-patch-old");
  console.log(`$ kill -TERM ${worker.pid}  # stop v1 after its first activity`);
  await env.stop(worker);
  console.log("$ (cd sdk && node --import tsx ../examples/evidence/worker.ts)  # blocked-v2.ts: activity('revisedStep')");
  worker = env.worker("blocked-v2.ts");
  env.cli("signal", "evidence-patch-old", "continue", "--input", "true");
  const blocked = await env.status("evidence-patch-old", "RUN_STATUS_BLOCKED");
  assert.match(blocked.failure.message, /history mismatch at event 5/);
  env.cli("describe", "evidence-patch-old");
  console.log("Viewing the mismatch for 3 real seconds.");
  await delay(3000);
  env.cli("history", "evidence-patch-old");
  console.log(`$ kill -TERM ${worker.pid}  # replace incompatible v2`);
  await env.stop(worker);
  console.log('Patched code: activity(patched("revised-step-v2") ? "revisedStep" : "step", ...)');
  console.log("Old histories take step; new histories record the marker and take revisedStep.");
  console.log("$ (cd sdk && node --import tsx ../examples/evidence/worker.ts)  # blocked-patched.ts");
  env.worker("blocked-patched.ts");
  env.cli("resume", "evidence-patch-old", "--reason", "deployed replay-safe patched branch");
  const oldRun = await env.status("evidence-patch-old", "RUN_STATUS_COMPLETED");
  assert.deepEqual(decode(oldRun.result), { value: 1 });
  const oldHistory = await env.history("evidence-patch-old");
  assert.deepEqual(oldHistory.slice(0, before.length), before);
  assert.equal(oldHistory.filter((e) => e.activityCompleted).length, 1);
  assert.equal(oldHistory.filter((e) => e.runBlocked).length, 1);
  assert.equal(oldHistory.filter((e) => e.runResumed).length, 1);
  env.cli("describe", "evidence-patch-old");
  console.log("Viewing the completed old run for 2 real seconds.");
  await delay(2000);
  env.cli("history", "evidence-patch-old");
  env.cli("start", "changedWorkflow", "evidence-patch-new", "--queue", env.queue);
  await env.rpc("SignalRun", { runId: "evidence-patch-new", name: "continue", input: payload(true) });
  const newRun = await env.status("evidence-patch-new", "RUN_STATUS_COMPLETED");
  assert.deepEqual(decode(newRun.result), { value: 10 });
  const newHistory = await env.history("evidence-patch-new");
  assert(newHistory.some((e) => e.markerRecorded?.markerId === "revised-step-v2"));
  env.cli("describe", "evidence-patch-new");
  console.log("Viewing the completed new run for 2 real seconds.");
  await delay(2000);
  env.cli("history", "evidence-patch-new");
  console.log("PASS: old run BLOCKED → explicit resume → COMPLETED (value 1, one activity completion); new run records patch marker and returns value 10.");
  console.log("Cleanup: stopping this demo's processes and dropping its database.");
});
